### ISSUE TITLE
Will sync with the new wrapper? 

### ISSUE THREAD

**Issue by cyrsis** [mbientlab/MetaWear-UwpStarter#1]
if (selectedDevice != null) {
                initFlyout.ShowAt(pairedDevices);
                var board = MetaWearBoard.getMetaWearBoardInstance(selectedDevice);
                board.Initialize(new FnVoid(async () => {
                    await CoreApplication.MainView.CoreWindow.Dispatcher.RunAsync(
                    CoreDispatcherPriority.Normal, () => {
                        initFlyout.Hide();
                        this.Frame.Navigate(typeof(DeviceSetup), selectedDevice);
                    });
                }));
            }

I cannot get FnVoid work in here with new nuget package

**Comment by scaryghost** [comment]
Please use the markdown syntax to format your code; it helps a lot with readability.

There are breaking changes for both the API and wrapper code in API v0.5.0.  You can read about them in the [release notes](https://github.com/mbientlab/Metawear-CppAPI/releases/tag/0.5.0).

**Comment by scaryghost** [comment]
FYI, the latest commit updates the repo to use API v0.5.22
